package de.hanno.hpengine.graphics.renderer.constants

import InternalTextureFormat
import InternalTextureFormat.*
import org.lwjgl.opengl.EXTTextureCompressionS3TC.GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
import org.lwjgl.opengl.EXTTextureSRGB.GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT
import org.lwjgl.opengl.EXTTextureSRGB.GL_SRGB8_ALPHA8_EXT
import org.lwjgl.opengl.GL30.*

val InternalTextureFormat.glValue: Int
    get() = when(this) {
        ALPHA4 -> GL_ALPHA4
        ALPHA8 -> GL_ALPHA8
        ALPHA12 -> GL_ALPHA12
        ALPHA16 -> GL_ALPHA16
        LUMINANCE4 -> GL_LUMINANCE4
        LUMINANCE8 -> GL_LUMINANCE8
        LUMINANCE12 -> GL_LUMINANCE12
        LUMINANCE16 -> GL_LUMINANCE16
        LUMINANCE4_ALPHA4 -> GL_LUMINANCE4_ALPHA4
        LUMINANCE6_ALPHA2 -> GL_LUMINANCE6_ALPHA2
        LUMINANCE8_ALPHA8 -> GL_LUMINANCE8_ALPHA8
        LUMINANCE12_ALPHA4 -> GL_LUMINANCE12_ALPHA4
        LUMINANCE12_ALPHA12 -> GL_LUMINANCE12_ALPHA12
        LUMINANCE16_ALPHA16 -> GL_LUMINANCE16_ALPHA16
        INTENSITY -> GL_INTENSITY
        INTENSITY4 -> GL_INTENSITY4
        INTENSITY8 -> GL_INTENSITY8
        INTENSITY12 -> GL_INTENSITY12
        INTENSITY16 -> GL_INTENSITY16
        R3_G3_B2 -> GL_R3_G3_B2
        RGB4 -> GL_RGB4
        RGB5 -> GL_RGB5
        RGB8 -> GL_RGB8
        RGB10 -> GL_RGB10
        RGB12 -> GL_RGB12
        RGB16 -> GL_RGB16
        RGBA2 -> GL_RGBA2
        RGBA4 -> GL_RGBA4
        RGB5_A1 -> GL_RGB5_A1
        RGBA8 -> GL_RGBA8
        RGB10_A2 -> GL_RGB10_A2
        RGBA12 -> GL_RGBA12
        RGBA16 -> GL_RGBA16
        TEXTURE_RED_SIZE -> GL_TEXTURE_RED_SIZE
        TEXTURE_GREEN_SIZE -> GL_TEXTURE_GREEN_SIZE
        TEXTURE_BLUE_SIZE -> GL_TEXTURE_BLUE_SIZE
        TEXTURE_ALPHA_SIZE -> GL_TEXTURE_ALPHA_SIZE
        TEXTURE_LUMINANCE_SIZE -> GL_TEXTURE_LUMINANCE_SIZE
        TEXTURE_INTENSITY_SIZE -> GL_TEXTURE_INTENSITY_SIZE
        PROXY_TEXTURE_1D -> GL_PROXY_TEXTURE_1D
        PROXY_TEXTURE_2D -> GL_PROXY_TEXTURE_2D
        RGBA32F -> GL_RGBA32F
        RGB32F -> GL_RGB32F
        RGBA16F -> GL_RGBA16F
        RGB16F -> GL_RGB16F
        DEPTH_COMPONENT24 -> GL_DEPTH_COMPONENT24
        COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT -> GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT
        COMPRESSED_RGBA_S3TC_DXT5_EXT -> GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
        SRGB8_ALPHA8_EXT -> GL_SRGB8_ALPHA8_EXT
        RG16F -> GL_RG16F
        R16I -> GL_R16I
        R32F -> GL_R32F
        DEPTH24_STENCIL8 -> GL_DEPTH24_STENCIL8
        DEPTH_COMPONENT -> GL_DEPTH_COMPONENT
    }